### ISSUE TITLE
Questions regarding Nitro ACM 

### ISSUE THREAD

**Issue by vasav03** [aws-samples/aws-nitro-enclaves-certificate-manager-sample#1]
**Q1 : Is it possible to host any application in ACM enclave  ?** 
  Now that we can run only one enclave in EC2 
  We are thinking if we could create an image which serves ACM requests and still respond to our custom service requests.
  Even if we create an Enclave image which hosts custom application and still support ACM,  Attestation PCRs will change.
  Can we know how the enclave image is created ? 
  
 
--------------------------------------------------------------------------------------------------------------------
 While trying to assoiate iam role to ACM certificate [ with below command ] 

>  aws ec2 --region us-east-1 associate-enclave-certificate-iam-role --certificate-arn arn:aws:acm:us-east-1:123456789012:certificate/d4c3b2a1-e5d0-4d51-95d9-1927fEXAMPLE --role-arn arn:aws:iam::123456789012:role/acm-role

 We get an output ;
```
 {

"CertificateS3BucketName": "aws-ec2-enclave-certificate-us-east-1",
"CertificateS3ObjectKey": "arn:aws:iam::123456789012:role/acm-role/arn:aws:acm:us-east-1:123456789012:certificate/d4c3b2a1-e5d0-4d51-95d9-1927fEXAMPLE",
"EncryptionKmsKeyId": "a1b2c3d4-354d-4e51-9190-b12ebEXAMPLE"
}
```

**Q2 :  Is the KMS Key Id mentioned be owned by AWS ?**
Will that Key have policy to allow ACM enclave to decrypt ie attestation based policy ?

**Comment by jdbean** [comment]
Q1: Modifications to the application code in an enclave image file  (EIF), such as adding additional custom application code, will result in changes to EIF PCRs. This is a feature of AWS Nitro Enclaves Cryptographic attestation.

Q2: The private key of the certificate is encrypted with an Amazon Web Services managed key that has an attached attestation-based key policy. See the [documentation reference for the AssociateEnclaveCertificateIamRole API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateEnclaveCertificateIamRole.html) for more information.

**Comment by vasav03** [comment]
Thanks for the quick reply.

Q2: The private key of the certificate is encrypted with an Amazon Web Services managed key that has an attached attestation-based key policy. See the documentation reference for the AssociateEnclaveCertificateIamRole API for more information.
>>
Found the steps( at least similar steps) used for creating Nitro ACM Enclave image from [https://github.com/aws/aws-nitro-enclaves-acm/tree/main/env](https://github.com/aws/aws-nitro-enclaves-acm/tree/main/env)

And also found below PCR measurements from SAM deployment and manual deployment of aws nitro enclaves certificate manager example ( This project ! )

`{
  "Measurements": {
    "HashAlgorithm": "Sha384 { ... }",
    "PCR0": "4643...6254",
    "PCR1": "ef5b....a2c70",
    "PCR2": "bdd6....4e79",
    "PCR8": "c58e....e0c8"
  }
}`

So the AWS managed KMS Key which has attestation based policy would have above eif or measurement details in the attestation. 

If we somehow add features to Nitro ACM ( by adding code to https://github.com/aws/aws-nitro-enclaves-acm/tree/main/env/enclave) then PCR measurements will change and Enclave will not be grant KMS:decrypt and the whole ACM support will fail.

The conclusion is  "We cannot have one Enclave image which supports ACM opertarions (ie. p11-kit-server) and a simple hello world or echo or any other service since KMS attestation based policy is FIXED "
